# Generated by Django 4.0.1 on 2022-01-28 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalized',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='ID')),
                ('shortened_url', models.SlugField(unique=True)),
                ('long_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.SlugField(unique=True)),
                ('long_url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Urls',
            },
        ),
    ]
